apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: jenkins-pvc
          persistentVolumeClaim:
            claimName: jenkins-pvc
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
          - name: jenkins-web
            protocol: TCP
            containerPort: 8080
          - name: jenkins-agent
            protocol: TCP
            containerPort: 50000
        volumeMounts:
          - name: jenkins-pvc
            mountPath: "/var/jenkins_home"
