apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: jenkins-pv
  storageClassName: longhorn-hdd
  accessModes:
    - ReadWriteOnce
