apiVersion: v1
kind: Service
metadata:
  name: jenkins-api
  namespace: jenkins
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: jenkins-web
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort